INSERT INTO USERS (ID, EMAIL, NAME, PASSWORD, ROLE, STATUS, DTYPE) VALUES (x'02850F15B6A946F9990E1540691F088B', 'admin@email.com', 'Administrador Geral', '$2a$10$PKbIAVV3lw9y23GjGDz0ouCNGQIrPNKaCYhDS7DnTXHOmQQz5lTk6', 'ROLE_ADMIN', 'A', 'User');
INSERT INTO USERS (ID, EMAIL, NAME, PASSWORD, ROLE, STATUS, DTYPE) VALUES (x'B299D403A03145DC9A7CCBFAF1BD823F', 'funcionario1@email.com', 'Funcionário 1', '$2a$10$PKbIAVV3lw9y23GjGDz0ouCNGQIrPNKaCYhDS7DnTXHOmQQz5lTk6', 'ROLE_EMPLOYEE', 'A', 'User');
INSERT INTO USERS (ID, EMAIL, NAME, PASSWORD, ROLE, STATUS, DTYPE) VALUES (x'14BAC90FE8F44A3294D80B1A5E01F444', 'cliente1@email.com', 'Cliente Teste', '$2a$10$PKbIAVV3lw9y23GjGDz0ouCNGQIrPNKaCYhDS7DnTXHOmQQz5lTk6', 'ROLE_CLIENT', 'P', 'Client');
INSERT INTO product (id, name, description, unit_price) VALUES (1,'Alho e Óleo','Mussarela, alho e óleo.','35');
INSERT INTO product (id, name, description, unit_price) VALUES (2,'Bacon','Mussarela, bacon e milho.','35');
INSERT INTO product (id, name, description, unit_price) VALUES (3,'Calabresa','Mussarela e calabresa.','35');
INSERT INTO product (id, name, description, unit_price) VALUES (4,'Escarola','Mussarela, escarola, bacon e catupiry.','35');
INSERT INTO product (id, name, description, unit_price) VALUES (5,'Frango Catupiry','Mussarela, frango desfiado e requeijão tipo catupiry.','40');
INSERT INTO product (id, name, description, unit_price) VALUES (6,'Lombo Catupiry','Mussarela, lombinho e requeijão tipo catupiry.','40');
INSERT INTO product (id, name, description, unit_price) VALUES (7,'Napolitana','Mussarela, tomate e parmesão.','35');
INSERT INTO product (id, name, description, unit_price) VALUES (8,'Portuguesa','Mussarela, presunto, cebola, ovo e azeitona preta.','50');
INSERT INTO product (id, name, description, unit_price) VALUES (9,'Quatro Queijos','Mussarela, parmesão, provolone e gorgonzola.','60');
